import Init

/-!
A small, dependency-free Lean 4 model of typed UI ports, identity links,
bindings as quotient classes, and a widget interpretation that factors
through the quotient.

The intended picture is:

  local typed ports --project--> shared binding --f--> widget

The relation `Linked` is the equivalence closure generated by two declared
links. `Binding t` is the quotient of ports of type `t` by that relation.
-/

namespace PortBindings

/-- Semantic payload types carried by ports. -/
inductive PortType where
  | document
  | selection
  deriving Repr, DecidableEq

/--
Typed local port occurrences. The index prevents an identity link between,
for example, a document port and a selection port.
-/
inductive Port : PortType → Type where
  | chartDocument    : Port .document
  | pipelineDocument : Port .document
  | tableDocument    : Port .document
  | chartSelection   : Port .selection

/--
The equivalence relation generated by the declared identity links.

The primitive edges are:

  chartDocument    ~ pipelineDocument
  pipelineDocument ~ tableDocument

The remaining constructors close the relation under reflexivity, symmetry,
and transitivity.
-/
inductive Linked : {t : PortType} → Port t → Port t → Prop where
  | refl {t : PortType} (p : Port t) : Linked p p
  | chart_pipeline :
      Linked Port.chartDocument Port.pipelineDocument
  | pipeline_table :
      Linked Port.pipelineDocument Port.tableDocument
  | symm {t : PortType} {p q : Port t} :
      Linked p q → Linked q p
  | trans {t : PortType} {p q r : Port t} :
      Linked p q → Linked q r → Linked p r

/-- The generated link relation is a setoid for each semantic port type. -/
def portSetoid (t : PortType) : Setoid (Port t) where
  r := Linked
  iseqv := {
    refl := fun p => Linked.refl p
    symm := fun h => Linked.symm h
    trans := fun h₁ h₂ => Linked.trans h₁ h₂
  }

/--
A binding is an equivalence class of linked local ports. In `Type`, this is
the concrete quotient/coequalizer used by the wiring compiler.
-/
abbrev Binding (t : PortType) := Quotient (portSetoid t)

/-- The quotient projection from a local port occurrence to its binding. -/
def project {t : PortType} (p : Port t) : Binding t :=
  Quotient.mk (portSetoid t) p

/-- Linked ports are identified by the quotient projection. -/
theorem linked_ports_same_binding
    {t : PortType} {p q : Port t}
    (h : Linked p q) :
    project p = project q := by
  exact Quotient.sound h

/-- A tiny semantic widget language. -/
inductive Widget where
  | documentPicker (title : String)
  | selectionBadge (title : String)
  deriving Repr, DecidableEq

/--
A local interpretation of ports as widgets. Notice that all three linked
document ports receive the same widget value.
-/
def rawWidget {t : PortType} : Port t → Widget
  | .chartDocument    => .documentPicker "Shared document"
  | .pipelineDocument => .documentPicker "Shared document"
  | .tableDocument    => .documentPicker "Shared document"
  | .chartSelection   => .selectionBadge "Chart selection"

/-- The local widget interpretation respects every generated link. -/
theorem rawWidget_respects
    {t : PortType} {p q : Port t}
    (h : Linked p q) :
    rawWidget p = rawWidget q := by
  induction h with
  | refl p =>
      rfl
  | chart_pipeline =>
      rfl
  | pipeline_table =>
      rfl
  | symm h ih =>
      exact ih.symm
  | trans h₁ h₂ ih₁ ih₂ =>
      exact ih₁.trans ih₂

/--
Existence part of the quotient's universal property: every port-level map
that respects `Linked` factors through `Binding`.
-/
def factor
    {t : PortType} {α : Type}
    (g : Port t → α)
    (respects : ∀ p q, Linked p q → g p = g q) :
    Binding t → α :=
  Quotient.lift g respects

/-- The factorization commutes with the quotient projection. -/
theorem factor_commutes
    {t : PortType} {α : Type}
    (g : Port t → α)
    (respects : ∀ p q, Linked p q → g p = g q)
    (p : Port t) :
    factor g respects (project p) = g p := by
  rfl

/--
Uniqueness part of the universal property: a map out of `Binding` is uniquely
determined by how it acts after the projection from local ports.
-/
theorem factor_unique
    {t : PortType} {α : Type}
    (g : Port t → α)
    (respects : ∀ p q, Linked p q → g p = g q)
    (u : Binding t → α)
    (commutes : ∀ p, u (project p) = g p) :
    u = factor g respects := by
  funext b
  refine Quotient.ind (s := portSetoid t) ?_ b
  intro p
  simpa [factor, project] using commutes p

/-- The widget interpretation lifted from ports to shared bindings. -/
def widgetOfBinding {t : PortType} : Binding t → Widget :=
  factor rawWidget (fun _ _ h => rawWidget_respects h)

/-- A port shows a widget by projecting to its binding and interpreting it. -/
def showWidget {t : PortType} (p : Port t) : Widget :=
  widgetOfBinding (project p)

/-- The requested concrete function `f` for document bindings. -/
def f : Binding .document → Widget :=
  widgetOfBinding

/-- The triangle `Port -> Binding -> Widget` commutes. -/
theorem f_commutes (p : Port .document) :
    f (project p) = rawWidget p := by
  rfl

/-- The two primitive chart/pipeline endpoints have one binding. -/
theorem chart_pipeline_same_binding :
    project Port.chartDocument = project Port.pipelineDocument := by
  exact linked_ports_same_binding Linked.chart_pipeline

/-- Transitivity identifies chart, pipeline, and table document ports. -/
theorem chart_table_same_binding :
    project Port.chartDocument = project Port.tableDocument := by
  apply linked_ports_same_binding
  exact Linked.trans Linked.chart_pipeline Linked.pipeline_table

/-- Therefore the linked chart and pipeline project to the same widget. -/
theorem chart_pipeline_same_widget :
    f (project Port.chartDocument) =
      f (project Port.pipelineDocument) := by
  exact congrArg f chart_pipeline_same_binding

/-- And the concrete widget is the shared document picker. -/
theorem chart_widget_is_document_picker :
    f (project Port.chartDocument) =
      Widget.documentPicker "Shared document" := by
  rfl

/-- A tiny HTML-like renderer, outside the quotient proof itself. -/
def Widget.render : Widget → String
  | .documentPicker title =>
      "<select aria-label=\"" ++ title ++ "\">Document</select>"
  | .selectionBadge title =>
      "<span role=\"status\">" ++ title ++ "</span>"

end PortBindings

open PortBindings

/-- Run with `lean --run Main.lean`. -/
def main : IO Unit := do
  IO.println ("chart:    " ++ Widget.render (f (project Port.chartDocument)))
  IO.println ("pipeline: " ++ Widget.render (f (project Port.pipelineDocument)))
  IO.println ("table:    " ++ Widget.render (f (project Port.tableDocument)))
