#!/usr/bin/env python3
"""
Complete token analysis by hour - showing input, output, cached, total, and billing.
"""

import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path

def extract_tokens_by_hour(filepath, session_name):
    """Extract glm-5.1 token usage by hour from a minitrace file."""
    hourly_stats = defaultdict(lambda: {
        "calls": 0, "input": 0, "output": 0, "cache_read": 0
    })

    with open(filepath, 'r') as f:
        data = json.load(f)

    for turn in data.get('turns', []):
        if turn.get('model') != 'glm-5.1':
            continue

        usage = turn.get('usage')
        if not usage:
            continue

        timestamp = turn.get('timestamp')
        if not timestamp:
            continue

        try:
            dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
            hour_key = dt.strftime('%Y-%m-%d %H:00')

            hourly_stats[hour_key]["calls"] += 1
            hourly_stats[hour_key]["input"] += usage.get('input_tokens', 0) or 0
            hourly_stats[hour_key]["output"] += usage.get('output_tokens', 0) or 0
            hourly_stats[hour_key]["cache_read"] += usage.get('cache_read_tokens', 0) or 0

        except (ValueError, AttributeError):
            continue

    return hourly_stats

def main():
    sessions = [
        ("d5862158 (8080-rom, Apr 15)", "/tmp/minitrace-analysis/pi-sessions/active/2026-04/d5862158-d05b-49ac-b6be-15e9795c1a67.minitrace.json"),
        ("2035dd97 (crib-k3s, Apr 16)", "/tmp/minitrace-analysis/pi-sessions/active/2026-04/2035dd97-cfb1-47ba-a90d-41096ae624d5.minitrace.json"),
        ("07fe66a4 (pinocchiorc, Apr 16)", "/tmp/minitrace-analysis/pi-sessions/active/2026-04/07fe66a4-97ee-4b3a-a802-da3b615bc9f2.minitrace.json"),
    ]

    all_hours = defaultdict(lambda: {
        "calls": 0, "input": 0, "output": 0, "cache_read": 0
    })

    print("=" * 120)
    print("GLM-5.1 TOKEN USAGE BY HOUR (April 15-16, 2026)")
    print("=" * 120)
    print()
    print("Token Types:")
    print("  • Input:    New tokens sent to API (billed)")
    print("  • Output:   Tokens generated by API (billed)")
    print("  • Cached:   Reused context (discounted/free)")
    print("  • Total:    Input + Output + Cached (all tokens processed)")
    print("  • Billing:  Input + Output (what you pay for)")
    print()

    for session_name, filepath in sessions:
        if not Path(filepath).exists():
            continue

        hourly = extract_tokens_by_hour(filepath, session_name)

        for date_hour in hourly.keys():
            h = hourly[date_hour]
            all_hours[date_hour]["calls"] += h["calls"]
            all_hours[date_hour]["input"] += h["input"]
            all_hours[date_hour]["output"] += h["output"]
            all_hours[date_hour]["cache_read"] += h["cache_read"]

    # Combined table with all token types
    print("=" * 120)
    print("COMPLETE HOURLY BREAKDOWN - ALL TOKEN TYPES")
    print("=" * 120)
    print()
    print(f"{'Hour':<18} {'Calls':>7} {'Input':>10} {'Output':>10} {'Cached':>12} {'Total':>12} {'Billing':>10}")
    print("-" * 120)

    totals = {"calls": 0, "input": 0, "output": 0, "cache_read": 0}

    for hour in sorted(all_hours.keys()):
        h = all_hours[hour]
        total = h["input"] + h["output"] + h["cache_read"]
        billing = h["input"] + h["output"]

        totals["calls"] += h["calls"]
        totals["input"] += h["input"]
        totals["output"] += h["output"]
        totals["cache_read"] += h["cache_read"]

        print(f"{hour:<18} {h['calls']:>7} {h['input']:>10,} {h['output']:>10,} {h['cache_read']:>12,} {total:>12,} {billing:>10,}")

    print("-" * 120)
    grand_total = totals["input"] + totals["output"] + totals["cache_read"]
    grand_billing = totals["input"] + totals["output"]
    print(f"{'TOTAL':<18} {totals['calls']:>7} {totals['input']:>10,} {totals['output']:>10,} {totals['cache_read']:>12,} {grand_total:>12,} {grand_billing:>10,}")

    # Percentage breakdown by hour
    print()
    print("=" * 120)
    print("BILLING TOKEN DISTRIBUTION (% OF TOTAL)")
    print("=" * 120)
    print(f"{'Hour':<18} {'Billing':>12} {'% of Total':>12} {'Visual Bar':>50}")
    print("-" * 120)

    for hour in sorted(all_hours.keys()):
        h = all_hours[hour]
        billing = h["input"] + h["output"]
        pct = 100.0 * billing / grand_billing if grand_billing > 0 else 0
        bar_len = int(50 * pct / 100)
        bar = '█' * bar_len
        print(f"{hour:<18} {billing:>12,} {pct:>11.1f}% {bar}")

    # Daily summary
    print()
    print("=" * 120)
    print("DAILY SUMMARY - ALL TOKEN TYPES")
    print("=" * 120)
    print(f"{'Date':<12} {'Calls':>8} {'Input':>12} {'Output':>12} {'Cached':>14} {'Total':>14} {'Billing':>12}")
    print("-" * 120)

    daily = defaultdict(lambda: {"calls": 0, "input": 0, "output": 0, "cache_read": 0})
    for hour, h in all_hours.items():
        day = hour.split()[0]
        daily[day]["calls"] += h["calls"]
        daily[day]["input"] += h["input"]
        daily[day]["output"] += h["output"]
        daily[day]["cache_read"] += h["cache_read"]

    for day in sorted(daily.keys()):
        d = daily[day]
        total = d["input"] + d["output"] + d["cache_read"]
        billing = d["input"] + d["output"]
        print(f"{day:<12} {d['calls']:>8,} {d['input']:>12,} {d['output']:>12,} {d['cache_read']:>14,} {total:>14,} {billing:>12,}")

    print()
    print("=" * 120)
    print("NOTES:")
    print("  • Billing = Input + Output (what you pay for)")
    print("  • Total = Input + Output + Cached (all tokens the model sees)")
    print("  • Cached tokens are typically 50-90% cheaper or free")
    print(f"  • Cache ratio: {100.0 * totals['cache_read'] / grand_total:.1f}% of all tokens are cached context")
    print("=" * 120)

if __name__ == "__main__":
    main()
