import Init

/-!
# P06 mechanized core: typed ports, quotient bindings, resources, and widgets

This file is intentionally dependency-free.  It models the finite core used by
P06 without claiming to verify the TypeScript implementation.

The semantic triangle is

    Port c  --project-->  Binding c  --resourceOfBinding-->  Resource
                                              |
                                              v
                                            Widget

`Binding c` is a quotient by the equivalence relation generated by declared
identity links.  The contract index `c` prevents an identity link between
ports with different semantic contracts from being stated.
-/

namespace P06

/-- Identity-relevant semantic contracts.  Two contracts may use the same
runtime representation and still remain different contract fibers. -/
inductive Contract where
  | primaryDocument
  | rowSelection
  | derivedDocument
  deriving Repr, DecidableEq

/-- Local port occurrences indexed by their complete identity contract. -/
inductive Port : Contract → Type where
  | chartDocument         : Port .primaryDocument
  | pipelineDocument      : Port .primaryDocument
  | tableDocument         : Port .primaryDocument
  | chartSelection        : Port .rowSelection
  | tableSelection        : Port .rowSelection
  | pipelineOutputDocument : Port .derivedDocument

/--
The generated equivalence relation.  Primitive constructors are the stored
link declarations; reflexive, symmetric, and transitive constructors form the
smallest equivalence relation containing them.
-/
inductive Linked : {c : Contract} → Port c → Port c → Prop where
  | refl {c : Contract} (p : Port c) : Linked p p
  | chart_pipeline : Linked Port.chartDocument Port.pipelineDocument
  | pipeline_table : Linked Port.pipelineDocument Port.tableDocument
  | symm {c : Contract} {p q : Port c} : Linked p q → Linked q p
  | trans {c : Contract} {p q r : Port c} :
      Linked p q → Linked q r → Linked p r

/-- One setoid in every contract fiber. -/
def portSetoid (c : Contract) : Setoid (Port c) where
  r := Linked
  iseqv := {
    refl := fun p => Linked.refl p
    symm := fun h => Linked.symm h
    trans := fun h₁ h₂ => Linked.trans h₁ h₂
  }

/-- The quotient/coequalizer object for one contract fiber. -/
abbrev Binding (c : Contract) := Quotient (portSetoid c)

/-- The canonical quotient projection `q`. -/
def project {c : Contract} (p : Port c) : Binding c :=
  Quotient.mk (portSetoid c) p

/-- The coequalizer equation: related endpoints receive equal projections. -/
theorem linked_ports_same_binding
    {c : Contract} {p q : Port c}
    (h : Linked p q) :
    project p = project q := by
  exact Quotient.sound h

/-- A tiny rendering language used by the executable example. -/
inductive Widget where
  | documentPicker (label selected : String)
  | selectionBadge (label : String)
  | documentOutput (label selected : String)
  deriving Repr, DecidableEq

/-- A runtime resource allocated for a quotient class. -/
structure Resource where
  resourceId : String
  contract : Contract
  widget : Widget
  deriving Repr, DecidableEq

/--
A local interpretation before quotienting.  Every port in the generated
primary-document class maps to the same resource.  Unlinked ports may map to
independent resources.
-/
def rawResource {c : Contract} : Port c → Resource
  | .chartDocument =>
      { resourceId := "resource-primary-document"
        contract := .primaryDocument
        widget := .documentPicker "Chart document" "doc-a" }
  | .pipelineDocument =>
      { resourceId := "resource-primary-document"
        contract := .primaryDocument
        widget := .documentPicker "Chart document" "doc-a" }
  | .tableDocument =>
      { resourceId := "resource-primary-document"
        contract := .primaryDocument
        widget := .documentPicker "Chart document" "doc-a" }
  | .chartSelection =>
      { resourceId := "resource-chart-selection"
        contract := .rowSelection
        widget := .selectionBadge "Chart selection" }
  | .tableSelection =>
      { resourceId := "resource-table-selection"
        contract := .rowSelection
        widget := .selectionBadge "Table selection" }
  | .pipelineOutputDocument =>
      { resourceId := "resource-pipeline-output"
        contract := .derivedDocument
        widget := .documentOutput "Pipeline output" "doc-derived" }

/-- The local resource interpretation respects the generated relation. -/
theorem rawResource_respects
    {c : Contract} {p q : Port c}
    (h : Linked p q) :
    rawResource p = rawResource q := by
  induction h with
  | refl p =>
      rfl
  | chart_pipeline =>
      rfl
  | pipeline_table =>
      rfl
  | symm h ih =>
      exact ih.symm
  | trans h₁ h₂ ih₁ ih₂ =>
      exact ih₁.trans ih₂

/--
Existence part of the quotient universal property.  Every link-respecting
port interpretation factors through `Binding`.
-/
def factor
    {c : Contract} {α : Type}
    (g : Port c → α)
    (respects : ∀ p q, Linked p q → g p = g q) :
    Binding c → α :=
  Quotient.lift g respects

/-- The factorization triangle commutes. -/
theorem factor_commutes
    {c : Contract} {α : Type}
    (g : Port c → α)
    (respects : ∀ p q, Linked p q → g p = g q)
    (p : Port c) :
    factor g respects (project p) = g p := by
  rfl

/--
Uniqueness part of the universal property.  A map out of the quotient is
fully determined by its composite with `project`.
-/
theorem factor_unique
    {c : Contract} {α : Type}
    (g : Port c → α)
    (respects : ∀ p q, Linked p q → g p = g q)
    (u : Binding c → α)
    (commutes : ∀ p, u (project p) = g p) :
    u = factor g respects := by
  funext b
  refine Quotient.ind (s := portSetoid c) ?_ b
  intro p
  simpa [factor, project] using commutes p

/-- The runtime-resource interpretation induced on quotient classes. -/
def resourceOfBinding {c : Contract} : Binding c → Resource :=
  factor rawResource (fun _ _ h => rawResource_respects h)

/-- The requested binding-to-widget function. -/
def f : Binding .primaryDocument → Widget :=
  fun binding => (resourceOfBinding binding).widget

/-- Local projection followed by allocation agrees with the raw interpreter. -/
theorem resource_projection_commutes
    {c : Contract} (p : Port c) :
    resourceOfBinding (project p) = rawResource p := by
  rfl

/-- Chart and pipeline document ports inhabit one quotient class. -/
theorem chart_pipeline_same_binding :
    project Port.chartDocument = project Port.pipelineDocument := by
  exact linked_ports_same_binding Linked.chart_pipeline

/-- Transitive closure also identifies chart and table document ports. -/
theorem chart_table_same_binding :
    project Port.chartDocument = project Port.tableDocument := by
  apply linked_ports_same_binding
  exact Linked.trans Linked.chart_pipeline Linked.pipeline_table

/-- Equal binding projections allocate/observe the same resource. -/
theorem chart_pipeline_same_resource :
    resourceOfBinding (project Port.chartDocument) =
      resourceOfBinding (project Port.pipelineDocument) := by
  exact congrArg resourceOfBinding chart_pipeline_same_binding

/-- Consequently the two component-local names render the same widget. -/
theorem chart_pipeline_same_widget :
    f (project Port.chartDocument) =
      f (project Port.pipelineDocument) := by
  exact congrArg f chart_pipeline_same_binding

/-- The concrete projected widget in this executable model. -/
theorem chart_widget_is_document_picker :
    f (project Port.chartDocument) =
      Widget.documentPicker "Chart document" "doc-a" := by
  rfl

/-- An HTML-like renderer, outside the quotient proof itself. -/
def Widget.render : Widget → String
  | .documentPicker label selected =>
      "<label>" ++ label ++
      "<select><option selected>" ++ selected ++ "</option></select></label>"
  | .selectionBadge label =>
      "<span role=\"status\">" ++ label ++ "</span>"
  | .documentOutput label selected =>
      "<output aria-label=\"" ++ label ++ "\">" ++ selected ++ "</output>"

end P06

open P06

/-- Run with `lean --run Main.lean`. -/
def main : IO Unit := do
  IO.println ("chart:    " ++ Widget.render (f (project Port.chartDocument)))
  IO.println ("pipeline: " ++ Widget.render (f (project Port.pipelineDocument)))
  IO.println ("table:    " ++ Widget.render (f (project Port.tableDocument)))
